version: "3.8"

services:
  app:
    build: 
      context: .
    volumes: 
      - .:/frontend
    ports:
      - 3000:3000
    image: app:frontend
    container_name: react_container
    command: npm start
    