# Generated by Django 4.0.4 on 2022-06-25 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('location', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('address', models.TextField(max_length=164)),
                ('email', models.EmailField(max_length=164)),
                ('business_hours', models.CharField(blank=True, max_length=164, null=True)),
                ('is_vendor', models.BooleanField(default=True)),
                ('is_auditor', models.BooleanField(default=False)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user', models.ManyToManyField(related_name='managed_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
